
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "http://evaluacion-oauth2:9000"
            client:
                registration:
                    client-app:
                        provider: spring
                        client-id: client-app
                        client-secret: 12345
                        authorization-grant-type: authorization_code

                        redirect-uri: "http://evaluacion-oauth2:8081/authorized"
                        scope: 
                            - openid
                            - profile
                            - read
                            - write
                        client-name: client-app
                provider:
                    spring:
                        issuer-uri: "http://evaluacion-oauth2:9000"
